### ISSUE TITLE
2018.4.20 佐々木さんlunch

### ISSUE THREAD

**Issue by yamazakiopst** [ebook-okazaki/git-training#1]
## 作業内容
04/20の佐々木さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、[ebook-okazaki/git-training-lunch](https://github.com/ebook-okazaki/git-training-lunch)リポジトリで行う

※
- ebook-okazaki/git-training-lunchリポジトリにはissueを作成しない
- ebook-okazaki/git-training-lunchリポジトリ内に作成したPRは、[ebook-okazaki/git-trainingリポジトリのissueにconnectさせる

`git-training/#{N}-{name}-lunch` ブランチで作業を行い、`origin/master` ブランチへPRしてマージする

コミットメッセージは、 `ebook-okazaki/git-training#{N} 誰の昼食か（どんな修正か）` の形式にする

PRのタイトルは、

- `git-training/#{N}-{name}-lunchからmasterへのマージ(git-training/#{N})`

以上の形式とする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-training-lunch-oka-pr-{N}.herokuapp.com/
本番環境 | https://git-training-lunch-oka.herokuapp.com/

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：山崎
- branch作成者：佐々木
- 開発担当者(昼食報告、1名)：佐々木
- 検収担当者：山崎
- リリース担当者：佐々木

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [x] 検収担当者が、issueをcloseした

**Comment by opst-sasakih** [comment]
リリースタグの設定を行いました。
https://github.com/ebook-okazaki/git-training-lunch/releases

**Comment by opst-sasakih** [comment]
本番環境へデプロイされていることを確認しました。
![honban](https://user-images.githubusercontent.com/38517501/39170416-6bd91994-47d6-11e8-9716-98deded066a7.png)

**Comment by yamazakiopst** [comment]
@opst-sasakih 確認しましたのでクローズします
