### ISSUE TITLE
2018.06.25-2018.06.25 佐藤さんlunch

### ISSUE THREAD

**Issue by opst-shinozaki** [ebook-okazaki/git-training#14]
## 作業内容
06/25の佐藤さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、[ebook-okazaki/git-training-lunch](https://github.com/ebook-okazaki/git-training-lunch)リポジトリで行う

※
- ebook-okazaki/git-training-lunchリポジトリにはissueを作成しない
- ebook-okazaki/git-training-lunchリポジトリ内に作成したPRは、[ebook-okazaki/git-trainingリポジトリのissueにconnectさせる

`git-training/#{N}-{name}-lunch` ブランチで作業を行い、`origin/master` ブランチへPRしてマージする

コミットメッセージは、 `ebook-okazaki/git-training#{N} 誰の昼食か（どんな修正か）` の形式にする

PRのタイトルは、

- `git-training/#{N}-{name}-lunchからmasterへのマージ(git-training/#{N})`

以上の形式とする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-training-lunch-oka-pr-{N}.herokuapp.com/
本番環境 | https://git-training-lunch-oka.herokuapp.com/

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：篠崎
- branch作成者：大内
- 開発担当者(昼食報告、1名)：大内
- 検収担当者：篠崎
- リリース担当者：大内

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] 開発担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [ ] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [ ] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [ ] 検収担当者が、issueをcloseした

**Comment by opst-satoh** [comment]
リリースタグの設定を行いました
https://github.com/ebook-okazaki/git-training-lunch/releases/tag/v6.5

**Comment by opst-satoh** [comment]
本番環境にデプロイされていることを確認しました。
![honban](https://user-images.githubusercontent.com/40283233/41883837-8395d1fe-792b-11e8-8632-fd25c3742a8c.PNG)

**Comment by opst-shinozaki** [comment]
確認しました。問題ないのでクローズします。
