### ISSUE TITLE
2018.05.07-2018.05.07 篠崎さんlunch

### ISSUE THREAD

**Issue by opst-sasakih** [ebook-okazaki/git-training#7]
## 作業内容
05/07の篠崎さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、[ebook-okazaki/git-training-lunch](https://github.com/ebook-okazaki/git-training-lunch)リポジトリで行う

※
- ebook-okazaki/git-training-lunchリポジトリにはissueを作成しない
- ebook-okazaki/git-training-lunchリポジトリ内に作成したPRは、[ebook-okazaki/git-trainingリポジトリのissueにconnectさせる

`git-training/#{N}-{name}-lunch` ブランチで作業を行い、`origin/master` ブランチへPRしてマージする

コミットメッセージは、 `ebook-okazaki/git-training#{N} 誰の昼食か（どんな修正か）` の形式にする

PRのタイトルは、

- `git-training/#{N}-{name}-lunchからmasterへのマージ(git-training/#{N})`

以上の形式とする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-training-lunch-oka-pr-{N}.herokuapp.com/
本番環境 | https://git-training-lunch-oka.herokuapp.com/

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：佐々木
- branch作成者：篠崎
- 開発担当者(昼食報告、1名)：篠崎
- 検収担当者：佐々木
- リリース担当者：篠崎

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [ ] 検収担当者が、issueをcloseした

**Comment by opst-shinozaki** [comment]
リリースタグv6.2を作成しました。

**Comment by opst-shinozaki** [comment]
master branch にデプロイしました。
https://git-training-lunch-oka.herokuapp.com/lunch/201805.html

**Comment by opst-shinozaki** [comment]
![image](https://user-images.githubusercontent.com/38833106/39739618-d440ecea-52cc-11e8-872c-361ed2e18862.png)

**Comment by opst-sasakih** [comment]
確認できました。
ありがとうございます。
