### ISSUE TITLE
2018.05.07-2018.05.07 堀尾さんlunch

### ISSUE THREAD

**Issue by opst-sasakih** [ebook-okazaki/git-training#8]
## 作業内容
05/07の堀尾さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、[ebook-okazaki/git-training-lunch](https://github.com/ebook-okazaki/git-training-lunch)リポジトリで行う

※
- ebook-okazaki/git-training-lunchリポジトリにはissueを作成しない
- ebook-okazaki/git-training-lunchリポジトリ内に作成したPRは、[ebook-okazaki/git-trainingリポジトリのissueにconnectさせる

`git-training/#{N}-{name}-lunch` ブランチで作業を行い、`origin/master` ブランチへPRしてマージする

コミットメッセージは、 `ebook-okazaki/git-training#{N} 誰の昼食か（どんな修正か）` の形式にする

PRのタイトルは、

- `git-training/#{N}-{name}-lunchからmasterへのマージ(git-training/#{N})`

以上の形式とする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-training-lunch-oka-pr-{N}.herokuapp.com/
本番環境 | https://git-training-lunch-oka.herokuapp.com/

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：佐々木
- branch作成者：堀尾
- 開発担当者(昼食報告、1名)：堀尾
- 検収担当者：佐々木
- リリース担当者：堀尾

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [ ] 検収担当者が、issueをcloseした

**Comment by opst-sasakih** [comment]
プルリク作成ありがとうございます。
以下指摘事項となります。
①判定基準の「heroku のreview app環境」のリンク先を変更してください。
②修正内容の「修正内容を記載」に修正内容の記載をお願いします。
③PRのreviewer,asighneeに検収者を設定してください。

**Comment by ghost** [comment]
リリースタグv6.3を作成しました。

**Comment by ghost** [comment]
![3](https://user-images.githubusercontent.com/38945472/39803387-6d8c8e20-5360-11e8-9d97-20b67503f154.PNG)

**Comment by opst-sasakih** [comment]
問題ないようなのでクローズします。
ありがとうございました。
